language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

env:
  - DB=mysql

mysql:
  database: clanify_test
  username: root
  password: 12345
  encoding: utf8

before_script:
  - mysql -e 'create database clanify_test'

script: phpunit

notifications:
  email:
    - support@clanify.rocks