language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mysql

env:
  - DB=mysql

mysql:
  database: clanify_test
  username: root
  encoding: utf8

before_script:
  - composer install
  - mysql -e 'create database clanify_test'
  - mysql clanify_test < resource/install.sql

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email:
    - support@clanify.rocks